development:
  clients:
    default:
      database: market_place_development
      hosts:
        - localhost:27017
      options:
  options:
production:
  clients:
    default:
      uri: ENV['MONGODB_URI']
    options:
      skip_version_check: true
    safe: true
  options:
test:
  clients:
    default:
      database: market_place_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
